name: "CheckStyle"

on: pull_request

jobs:
  checkStyle:
    name: CheckStyle
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run java checkstyle
      uses: nikitasavinov/checkstyle-action@0.3.1
      with:
        checkstyle_config: checkstyle.xml
        reporter: 'github-pr-check'
        tool_name: 'StyleReview'
