name: "Build and Deploy"

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to kio.ee
        run: echo "${{ secrets.KIO_TOKEN }}" | docker login -u "${{ secrets.KIO_ROBOT }}" --password-stdin kio.ee

      - name: Compile JAR
        run: mvn --batch-mode --update-snapshots clean package -P production-mode,noTesting

      - name: Pull latest base and build images
        run: docker pull kio.ee/hub/library/adoptopenjdk:15-jre-openj9

      - name: Docker build and tag
        run: docker build -f Dockerfile -t kio.ee/kyberorg/whoami:current .

      - name: Docker push
        run: docker push kio.ee/kyberorg/whoami:current

      - name: Delete pushed image to prevent mess
        run: docker rmi kio.ee/kyberorg/whoami:current
        continue-on-error: true

      - name: Deploy
        uses: wei/curl@master
        with:
          args: -X POST ${{ secrets.DEPLOY_HOOK }}
