name: "Build and Deploy"

on:
  push:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to kio.ee
        run: echo "${{ secrets.KIO_TOKEN }}" | docker login -u "${{ secrets.KIO_ROBOT }}" --password-stdin kio.ee

      - name: Compile JAR
        run: mvn --batch-mode --update-snapshots clean package -P production-mode

      - name: Pull latest base and build images
        run: docker pull kio.ee/lib/eclipse-temurin:17-jre-alpine

      - name: Docker build and tag
        run: docker build -f Dockerfile -t kio.ee/kyberorg/whoami:current .

      - name: Docker push
        run: docker push kio.ee/kyberorg/whoami:current

      - name: Get Docker image SHA256
        id: docker_image_sha
        run: echo "::set-output name=imageSha::$(docker images --digests | awk 'NR==2 {print $3}')"

      - name: Delete pushed image to prevent mess
        run: docker rmi kio.ee/kyberorg/whoami:current
        continue-on-error: true

      - name: Deploy
        uses: wei/curl@master
        with:
          args: -X POST ${{ secrets.DEPLOY_HOOK }}?tag=current@${{ steps.docker_image_sha.outputs.imageSha }}
